// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfbbobkizwcmglvkwkqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYmJvYmtpendjbWdsdmt3a3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTcyNjUsImV4cCI6MjA2NzA3MzI2NX0.eAvLPVJqDag3UMFDV5sMSa_X-awJ0N1DLLHPPV8zbEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});